
### Get 

GET http://localhost:3000/api/users/


### GetbyId
GET http://localhost:3000/api/user/1


### Get 
GET http://localhost:3000/api/event/


### Update Event
PATCH http://localhost:3000/api/event/1
Content-Type: application/json

{
    
  "name": "jean rachid",
  "owner_id": 5,
  "status" : true,
  "description": "super event !!!",
  "picture": "http://www.google.fr",
  "link_project": "http://www.google.fr"

}

### Delete Event
DELETE http://localhost:3000/api/event/1


### Post Event
POST http://localhost:3000/api/event
Content-Type: application/json

{
    
  "name": "zouzou",
  "password": "verge",
  "owner_id": 5,
  "status" : true,
  "description": "super event !!!",
  "picture": "http://www.google.fr",
  "link_project": "http://www.google.fr"

}



### Post User
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstname": "Testtest",
  "lastname": "MaSoeurtttt",
  "email": "Vive-Test@testexample.com",
  "password": "Password123!"
}

