
### Get 

GET http://localhost:3000/api/users/


### GetbyId
GET http://localhost:3000/api/user/1


### Get 
GET http://localhost:3000/api/event/


### Update Event
PATCH http://localhost:3000/api/event/1
Content-Type: application/json

{
    
  "name": "jean rachid",
  "ownerId": 5,
  "status" : true,
  "description": "super event !!!",
  "picture": "http://www.google.fr",
  "linkProject": "http://www.google.fr",
  "password": "verge"

}

### Delete Event
DELETE http://localhost:3000/api/event/1


### Post Event
POST http://localhost:3001/api/event
Content-Type: application/json

{
    
  "name": "Soirée alcoolisée et débauche",
  "ownerId": 5,
  "status" : true,
  "description": "super event !!!",
  "picture": "http://www.google.fr",
  "linkProject": "http://www.google.fr"

}



### Post User
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstname": "Geoffrey",
  "lastname": "Fardeau",
  "email": "frenchelectrolove@gmail.com",
  "password": "Password123!"
}



### Post UserChoice
POST http://localhost:3000/api/userchoice
Content-Type: application/json

{
  "startDate": "2023-12-27 15:30:00+03:00",
  "endDate": "2023-11-28 15:30:00+03:00",
  "eventId": 1,
  "userId": 1
}


### Get UserChoice by id
GET http://localhost:3000/api/userchoice/1

### Get all user choices
GET http://localhost:3000/api/userchoice



### Update userchoice
PATCH http://localhost:3000/api/userchoice/1
Content-Type: application/json

{
    
  "startDate": "2023-10-25 15:30:00+03:00",
  "endDate": "2023-10-25 15:30:00+03:00",
  "eventId": 1,
  "userId": 1

}


### Delete userchoice
DELETE http://localhost:3000/api/userchoice/4


### Delete user
DELETE http://localhost:3000/api/user/33
### Get 

GET http://localhost:3000/api/theme


### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "test@test.fr",
  "password": "Password123!"
}




### GetThemeById
GET http://localhost:3000/api/theme/1

### Delete Theme
DELETE http://localhost:3000/api/theme/5


### Post Theme
POST http://localhost:3000/api/theme
Content-Type: application/json

{
  "name": "Camping",
  "theme_id": 2
}


### Post user invation
POST http://localhost:3001/api/invitelink/
Content-Type: application/json

{
  "email": "renaud.berni@oclock.school",
  "eventId": "37"
}
